<?php

function wim2a_menu(){
    $items ['wim2a/page1/%'] = array (
        'page callback' => 'wim2a_page1',
        'access arguments' => array ('access content'),
        'type'=> MENU_CALLBACK,
    );    
    $items['wim2a/monformulaire'] = array(  
        'title' => 'Mon Formulaire',  
        'page callback' => 'drupal_get_form',  
        'page arguments' => array('wim2a_monformulaire'),  
        'access callback' => true,  
        'type' => MENU_CALLBACK,
    );
    $items['wim2a/pageformulaire'] = array(  
        'title' => 'Page Formulaire',  
        'page callback' => 'pageformulaire', //erreur?  
        'access callback' => true,  
        'type' => MENU_CALLBACK,
    );
  

    return $items;
}


function wim2a_page1($arg='none') {  
    $outputs['arg'] = $arg;  
    $outputs['request_uri'] = $_SERVER['REQUEST_URI'];  
    $outputs['query_string'] = $_SERVER['QUERY_STRING'];  
    $outputs['path_info'] = isset($_SERVER['PATH_INFO']) ? $_SERVER['PATH_INFO']                                                                                               
                                                        : 'non défini';  
     $outputs['script_name'] = $_SERVER['SCRIPT_NAME'];  
     $str = '';  foreach($outputs as $key => $value) {    
         $str .= $key . '<br>' . $value . '<br><br>';  
        }  
        return $str;
    }
function wim2a_monformulaire($form, &$form_state) { 


    $form['nom'] = array(     
        '#title' => 'Nom',    
        '#type' => 'textfield',
        '#required' => TRUE,
        '#size' => 60, 
        '#maxlength' => 128,
    );
    $form['prenom'] = array(     
        '#title' => 'Prenom',    
        '#type' => 'textfield',
        '#required' => TRUE,
        '#size' => 60, 
        '#maxlength' => 128,
    );

    $form['valider'] = array(
    '#title' => t('Validation'),
    '#type' => 'submit',
    '#value' => 'Valider',
    );
        return $form;
}  
function wim2a_monformulaire_validate( $form, &$form_state){
    //var_dump($form_state);
   if ($form_state['values']['nom'] == '') {
        form_set_error('nom', t('saisir un nom'));
 }
 if ($form_state['values']['prenom'] == '') {
 form_set_error('prenom', t('saisir un prénom'));
 }
 
}
function wim2a_monformulaire_submit( $form, &$form_state){
    $db = array (
        ':nom' => $form_state['values']['nom'],
        ':prenom' => $form_state['values']['prenom'],
    );
    $sql = 'INSERT INTO wim2_etudiant (nom, prenom) VALUES (:nom,:prenom)';
    db_query($sql, $db);
    drupal_set_message('Enregistrées');
}
function wim2a_pageformulaire() {  
    $form = array();  
    $form_state = array();  
    $page_array['paragraphe1'] = array(      
        '#prefix' => '<p>',      
        '#suffix' => '</p>',      
        '#markup' => 'Paragraphe avant le formulaire',  
    );  
   $page_array['form'] = drupal_get_form('wim2a_monformulaire');  
        $page_array['paragraphe2'] = array(      
            '#prefix' => '<p>',      
            '#suffix' => '</p>',      
            '#markup' => 'Paragraphe après le formulaire',  
        );  
        return $page_array;
    }
?>